"""chat settings and user conversation flag

Revision ID: 2cdcb2a2c589
Revises: 4c0d7a22344e
Create Date: 2019-10-20 19:17:44.930296

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2cdcb2a2c589"
down_revision = "4c0d7a22344e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column("join_filter", sa.Boolean(), server_default=sa.text("false"), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "start_conversation", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "start_conversation")
    op.drop_column("chats", "join_filter")
    # ### end Alembic commands ###
