"""add chat type column

Revision ID: 4c0d7a22344e
Revises: 4201ee77de3d
Create Date: 2019-10-16 23:14:43.280821

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c0d7a22344e"
down_revision = "4201ee77de3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "type")
    # ### end Alembic commands ###
