"""Added additional chat settings

Revision ID: 9d333f105ea0
Revises: c639acad707a
Create Date: 2021-12-12 19:59:22.610129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d333f105ea0'
down_revision = 'c639acad707a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('report_to_admins', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('chats', sa.Column('restrict_commands', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'restrict_commands')
    op.drop_column('chats', 'report_to_admins')
    # ### end Alembic commands ###
