"""add do_not_disturb column

Revision ID: d6553c0e950b
Revises: 2cdcb2a2c589
Create Date: 2019-10-21 21:06:28.079557

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d6553c0e950b"
down_revision = "2cdcb2a2c589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("do_not_disturb", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "do_not_disturb")
    # ### end Alembic commands ###
